languageCode = "en-us"
title = "NuKeeper"
theme = "hugo-theme-learn"
enableEmoji = true

[params]
  editURL = "https://github.com/NuKeeperDotnet/NuKeeper/edit/master/site/content/"
  description = "Documentation for NuKeeper"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = true

[outputs]
home = [ "HTML", "RSS", "JSON"]